# docker-compose.yml
version: "3"
services:
  test:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    links:
      - postgres
    environment:
      PGHOST: postgres
      PGDATABASE: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: ${PGPASSWORD}

  postgres:
    build: ./db
    logging:
      driver: none
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DATABASE: postgres
