# docker-compose.yml
version: "3"
services:
  app:
    build: ./app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      PG_HOST: postgres
      PG_DATABASE: postgres
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres

  postgres:
    build: ./db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
